### ISSUE TITLE
Unable to run this on 8th Gen cpu

### ISSUE THREAD

**Issue by fiorano10** [intel/ros_opencl_caffe#15]
I have a 8700T (OS - Ubuntu 16.04) with Intel UHD 630, only supported by OpenCL 2.1 . The GPU doesn't get recognized when running clcaffe, and I can only run the model on the CPU. When will the new gen GPU be supported?

**Comment by chaoli2** [comment]
@fiorano10 
This project is not up-to-date since we have limited resource to maintain it yet. 
I suggest you use [Intel OpenVINO toolkit](https://software.intel.com/en-us/openvino-toolkit) which already support 8th CPU. It integrates OpenCL and other deep learning solutions. It is more powerful and better supported by Intel.  We are also maintaining ROS/ROS2 packages for OpenVINO. Please see [ROS OpenVINO package](https://github.com/intel/ros_openvino_toolkit) and [ROS2 OpenVINO package](https://github.com/intel/ros2_openvino_toolkit). 
Kindly let us know your requirements. Hope these projects could help you:)
