### ISSUE TITLE
How use yolov2/3-tiny?

### ISSUE THREAD

**Issue by fiorano10** [intel/ros_opencl_caffe#18]
Is it possible to use yolov2-tiny or yolov3-tiny with the current implementation?

**Comment by chaoli2** [comment]
@fiorano10 
Due to limited resource, new features in this project will be supported in very low priority. Intel GPU features will be included in [ROS openvino package](https://github.com/intel/ros_openvino_toolkit). As you know, we are now refactoring code for the scalability of more models. After that, yolov2-tiny and yolov3-tiny should be easy to support.
