### ISSUE TITLE
catkin make failed

### ISSUE THREAD

**Issue by farbod1277** [intel/ros_opencl_caffe#19]
Hi,
I followed the instructions but got this error while trying to build realsense 2.0.0:

`/home/farbod/catkin_ws/src/realsense/realsense_ros_camera/src/realsense_camera_node.cpp: In member function ‘realsense_ros_camera::IMUInfo realsense_ros_camera::RealSenseCameraNodelet::getImuInfo(const stream_index_pair&)’:
/home/farbod/catkin_ws/src/realsense/realsense_ros_camera/src/realsense_camera_node.cpp:924:58: error: ‘class rs2::sensor’ has no member named ‘get_motion_intrinsics’
             auto imuIntrinsics = _sensors[stream_index]->get_motion_intrinsics(stream_index.first);
                                                          ^
realsense/realsense_ros_camera/CMakeFiles/realsense_ros_camera.dir/build.make:62: recipe for target 'realsense/realsense_ros_camera/CMakeFiles/realsense_ros_camera.dir/src/realsense_camera_node.cpp.o' failed
make[2]: *** [realsense/realsense_ros_camera/CMakeFiles/realsense_ros_camera.dir/src/realsense_camera_node.cpp.o] Error 1
CMakeFiles/Makefile2:3949: recipe for target 'realsense/realsense_ros_camera/CMakeFiles/realsense_ros_camera.dir/all' failed
make[1]: *** [realsense/realsense_ros_camera/CMakeFiles/realsense_ros_camera.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed
`

Could you please let me know what I'm doing wrong?
Thanks

**Comment by chaoli2** [comment]
@fiorano10
This project is not up-to-date since we have limited resource to maintain it yet.
I suggest you use [Intel OpenVINO toolkit](https://software.intel.com/en-us/openvino-toolkit) instead of OpenCL Caffe, which integrates OpenCL and other deep learning solutions. It is more powerful and better supported by Intel. We are also maintaining [ROS/ROS2 packages](https://github.com/intel/ros_openvino_toolkit) for OpenVINO. Please see [ROS OpenVINO package](https://github.com/intel/ros_openvino_toolkit) and [ROS2 OpenVINO package](https://github.com/intel/ros2_openvino_toolkit).

Let me know if any question. Hope these projects could help you:)

**Comment by farbod1277** [comment]
> @fiorano10
> This project is not up-to-date since we have limited resource to maintain it yet.
> I suggest you use [Intel OpenVINO toolkit](https://software.intel.com/en-us/openvino-toolkit) instead of OpenCL Caffe, which integrates OpenCL and other deep learning solutions. It is more powerful and better supported by Intel. We are also maintaining [ROS/ROS2 packages](https://github.com/intel/ros_openvino_toolkit) for OpenVINO. Please see [ROS OpenVINO package](https://github.com/intel/ros_openvino_toolkit) and [ROS2 OpenVINO package](https://github.com/intel/ros2_openvino_toolkit).
> 
> Let me know if any question. Hope these projects could help you:)

Thank you very much for getting back to me! I will try OpenVINO.
